### ISSUE TITLE
体验地址有吗

### ISSUE THREAD

**Issue by tomxiaoma** [passerby223/beer_server#1]
有体验地址嘛？数据库校验测试结果有吗

**Comment by hashqueue** [comment]
> 有体验地址嘛？数据库校验测试结果有吗

[体验地址](http://beer.wenbin.org.cn/#/login)  数据库校验测试结果这个功能还没做，最近没时间，以后会逐步完善。这个项目目前还只能算是一个demo，很多功能都不完善，只是实现了基本的一些功能。麻烦您体验的时候别随便修改(新增数据都没问题)我在里边已经创建过的数据哈，非常感谢。

**Comment by hashqueue** [comment]
close
